# Generated by Django 4.2.29 on 2026-03-16 04:49

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="preview_image",
            field=models.ImageField(upload_to=blog.models.post_image_upload_to),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="path",
            field=models.ImageField(upload_to=blog.models.post_image_upload_to),
        ),
    ]
