# Generated by Django 4.2.29 on 2026-03-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_category"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["-created_at"], name="idx_post_created_at_desc"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["category", "-created_at"], name="idx_post_cat_created_at_desc"
            ),
        ),
    ]
